# Generated by Django 4.2.30 on 2026-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('free_shipping_from', models.DecimalField(decimal_places=2, default=1500.0, help_text='Order subtotal threshold for free shipping (EGP)', max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=60.0, help_text='Standard shipping fee across Egypt (EGP)', max_digits=10)),
                ('vodafone_wallet_number', models.CharField(blank=True, default='', help_text="Store's 11-digit Vodafone Cash wallet number", max_length=20)),
                ('vodafone_merchant_name', models.CharField(default='Derma Bastion Official', help_text='Account name displayed to customers', max_length=100)),
                ('vodafone_is_configured', models.BooleanField(default=False, help_text='Mark True once real wallet number is set')),
                ('instapay_identifier', models.CharField(blank=True, default='', help_text='InstaPay Payment Address (IPA, e.g. dermabastion@instapay) or IBAN', max_length=100)),
                ('instapay_account_name', models.CharField(blank=True, default='Derma Bastion Official', max_length=100)),
                ('instapay_is_configured', models.BooleanField(default=False, help_text='Mark True once real InstaPay IPA is set')),
                ('card_provider_name', models.CharField(default='Paymob', help_text='PSP Provider (Paymob, Fawry, Kashier)', max_length=50)),
                ('card_live_connected', models.BooleanField(default=False, help_text='Whether live payment gateway processing is active')),
                ('contact_phone', models.CharField(default='+20 100 000 0000', max_length=30)),
                ('contact_whatsapp', models.CharField(default='201000000000', max_length=30)),
                ('contact_email', models.EmailField(default='hello@dermabastion.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/')),
                ('announcement_en', models.CharField(default='Free shipping on orders above {amount} {currency}', max_length=255)),
                ('announcement_ar', models.CharField(default='شحن مجاني للطلبات فوق {amount} {currency}', max_length=255)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
