from django.core.management.base import BaseCommand
from products.models import Product


PRODUCTS_DATA = [
    {
        "id": 1,
        "name": "Hyaluronic Acid Serum 30ml",
        "category": "Skin Care",
        "price": 550,
        "badge": "Best Seller",
        "badge_ar": "الأكثر مبيعاً",
        "description": "A lightweight serum that gives skin a fresh, hydrated look and feel.",
        "benefits": ["Lightweight, non-greasy texture", "Absorbs quickly", "Suitable for daily use"],
        "how_to_use": "Apply 2-3 drops to clean skin morning and evening, then follow with moisturizer.",
        "ingredients": "Water, Hyaluronic Acid, Glycerin, Panthenol.",
        "name_ar": "سيروم حمض الهيالورونيك 30 مل",
        "category_ar": "العناية بالبشرة",
        "description_ar": "سيروم خفيف يمنح البشرة مظهراً وملمساً منتعشاً ومرطباً.",
        "benefits_ar": ["قوام خفيف غير دهني", "سريع الامتصاص", "مناسب للاستخدام اليومي"],
        "how_to_use_ar": "ضع 2-3 قطرات على بشرة نظيفة صباحاً ومساءً، ثم استخدم المرطب.",
        "ingredients_ar": "ماء، حمض الهيالورونيك، جلسرين، بانثينول.",
        "is_best_seller": True,
    },
    {
        "id": 2,
        "name": "Niacinamide Serum 10% 30ml",
        "category": "Skin Care",
        "price": 475,
        "badge": "",
        "badge_ar": "",
        "description": "A balancing serum for a smoother-looking, more even skin tone.",
        "benefits": ["Helps skin look more even", "Lightweight formula", "Pairs well with a daily moisturizer"],
        "how_to_use": "Apply a few drops to clean skin once or twice a day, then moisturize.",
        "ingredients": "Water, Niacinamide, Zinc PCA, Glycerin.",
        "name_ar": "سيروم النياسيناميد 10% 30 مل",
        "category_ar": "العناية بالبشرة",
        "description_ar": "سيروم موازن لبشرة أنعم ولون أكثر تجانساً.",
        "benefits_ar": ["يساعد على توحيد مظهر البشرة", "تركيبة خفيفة", "يتناسب مع المرطب اليومي"],
        "how_to_use_ar": "ضع بضع قطرات على بشرة نظيفة مرة أو مرتين يومياً، ثم استخدم المرطب.",
        "ingredients_ar": "ماء، نياسيناميد، زنك PCA، جلسرين.",
        "is_best_seller": False,
    },
    {
        "id": 3,
        "name": "Gentle Cleansing Gel 200ml",
        "category": "Skin Care",
        "price": 295,
        "badge": "",
        "badge_ar": "",
        "description": "A soft daily cleanser that removes dirt and excess oil without a tight feeling.",
        "benefits": ["Gentle for daily use", "Rinses off cleanly", "Leaves skin feeling fresh"],
        "how_to_use": "Massage a small amount onto a damp face, then rinse with water.",
        "ingredients": "Water, Glycerin, Coco-Betaine, Panthenol.",
        "name_ar": "جل تنظيف لطيف 200 مل",
        "category_ar": "العناية بالبشرة",
        "description_ar": "غسول يومي ناعم يزيل الأوساخ والزيوت الزائدة دون إحساس بالشد.",
        "benefits_ar": ["لطيف للاستخدام اليومي", "يُشطف بسهولة", "يترك البشرة منتعشة"],
        "how_to_use_ar": "دلّك كمية صغيرة على وجه مبلل ثم اشطفه بالماء.",
        "ingredients_ar": "ماء، جلسرين، كوكو بيتين، بانثينول.",
        "is_best_seller": False,
    },
    {
        "id": 4,
        "name": "Daily Sunscreen SPF50 50ml",
        "category": "Skin Care",
        "price": 450,
        "badge": "New",
        "badge_ar": "جديد",
        "description": "A daily sunscreen with a light, comfortable finish.",
        "benefits": ["SPF50 protection", "Light feel under makeup", "Easy to reapply"],
        "how_to_use": "Apply generously 15 minutes before sun exposure and reapply every two hours.",
        "ingredients": "Water, UV Filters, Vitamin E, Glycerin.",
        "name_ar": "واقي شمس يومي SPF50 50 مل",
        "category_ar": "العناية بالبشرة",
        "description_ar": "واقي شمس يومي بقوام خفيف وملمس مريح.",
        "benefits_ar": ["حماية SPF50", "خفيف تحت المكياج", "سهل إعادة التطبيق"],
        "how_to_use_ar": "ضع كمية كافية قبل التعرض للشمس بـ 15 دقيقة، وأعد التطبيق كل ساعتين.",
        "ingredients_ar": "ماء، فلاتر الأشعة فوق البنفسجية، فيتامين E، جلسرين.",
        "is_best_seller": False,
    },
    {
        "id": 5,
        "name": "Intense Tonic Spray 125ml",
        "category": "Hair Care",
        "price": 700,
        "badge": "Best Seller",
        "badge_ar": "الأكثر مبيعاً",
        "description": "A leave-in scalp and hair tonic in an easy spray bottle.",
        "benefits": ["Easy spray application", "Non-sticky finish", "Fits into your daily routine"],
        "how_to_use": "Spray onto a clean scalp, massage gently, and do not rinse.",
        "ingredients": "Water, Panthenol, Caffeine, Glycerin.",
        "name_ar": "سبراي تونيك مكثف 125 مل",
        "category_ar": "العناية بالشعر",
        "description_ar": "تونيك للشعر وفروة الرأس بدون شطف، في عبوة سبراي سهلة.",
        "benefits_ar": ["تطبيق سهل بالرش", "ملمس غير لزج", "يناسب روتينك اليومي"],
        "how_to_use_ar": "رشّ على فروة رأس نظيفة ودلّكها برفق دون شطف.",
        "ingredients_ar": "ماء، بانثينول، كافيين، جلسرين.",
        "is_best_seller": True,
    },
    {
        "id": 6,
        "name": "Repair Hair Mask 250ml",
        "category": "Hair Care",
        "price": 450,
        "badge": "",
        "badge_ar": "",
        "description": "A rich mask that leaves hair feeling soft, smooth and easier to style.",
        "benefits": ["Deep conditioning feel", "Softer, smoother hair", "Ideal for weekly use"],
        "how_to_use": "After shampooing, apply to damp hair, leave for 5 minutes, then rinse well.",
        "ingredients": "Water, Cetearyl Alcohol, Shea Butter, Argan Oil.",
        "name_ar": "ماسك إصلاح الشعر 250 مل",
        "category_ar": "العناية بالشعر",
        "description_ar": "ماسك غني يمنح الشعر نعومة وليونة وسهولة في التصفيف.",
        "benefits_ar": ["إحساس بترطيب عميق", "شعر أنعم وأكثر نعومة", "مثالي للاستخدام الأسبوعي"],
        "how_to_use_ar": "بعد الشامبو، ضعه على شعر رطب واتركه 5 دقائق ثم اشطفه جيداً.",
        "ingredients_ar": "ماء، كيتيريل ألكحول، زبدة الشيا، زيت الأرجان.",
        "is_best_seller": False,
    },
    {
        "id": 7,
        "name": "Anti-Dandruff Shampoo 250ml",
        "category": "Hair Care",
        "price": 320,
        "badge": "",
        "badge_ar": "",
        "description": "A daily shampoo made to keep the scalp feeling clean and comfortable.",
        "benefits": ["Cleanses the scalp", "Rich, easy lather", "Suitable for regular use"],
        "how_to_use": "Massage into wet hair and scalp, leave for 2 minutes, then rinse.",
        "ingredients": "Water, Zinc Pyrithione, Sodium Laureth Sulfate, Glycerin.",
        "name_ar": "شامبو مضاد للقشرة 250 مل",
        "category_ar": "العناية بالشعر",
        "description_ar": "شامبو يومي يحافظ على فروة رأس نظيفة ومريحة.",
        "benefits_ar": ["ينظف فروة الرأس", "رغوة غنية وسهلة", "مناسب للاستخدام المنتظم"],
        "how_to_use_ar": "دلّكه على الشعر وفروة الرأس المبللين واتركه دقيقتين ثم اشطفه.",
        "ingredients_ar": "ماء، زنك بيريثيون، صوديوم لوريث سلفات، جلسرين.",
        "is_best_seller": False,
    },
    {
        "id": 8,
        "name": "Lashes Treatment Serum 10ml",
        "category": "Eye Care",
        "price": 550,
        "badge": "",
        "badge_ar": "",
        "description": "A conditioning serum for the lash line, applied as part of your nightly routine.",
        "benefits": ["Precision brush applicator", "Lightweight formula", "Easy nightly routine"],
        "how_to_use": "Apply a thin line along the clean, dry upper lash line before bed.",
        "ingredients": "Water, Panthenol, Biotin, Glycerin.",
        "name_ar": "سيروم علاج الرموش 10 مل",
        "category_ar": "العناية بالعيون",
        "description_ar": "سيروم مغذٍّ لخط الرموش، يُستخدم ضمن روتينك الليلي.",
        "benefits_ar": ["فرشاة دقيقة للتطبيق", "تركيبة خفيفة", "سهل الاستخدام ليلاً"],
        "how_to_use_ar": "ضع خطاً رفيعاً على خط الرموش العلوي النظيف والجاف قبل النوم.",
        "ingredients_ar": "ماء، بانثينول، بيوتين، جلسرين.",
        "is_best_seller": False,
    },
]


class Command(BaseCommand):
    help = "Seed initial Derma Bastion products matching the frontend catalog"

    def handle(self, *args, **options):
        self.stdout.write("Seeding products...")
        count = 0
        for item in PRODUCTS_DATA:
            p_id = item.pop("id")
            product, created = Product.objects.update_or_create(
                id=p_id,
                defaults=item
            )
            count += 1
            action = "Created" if created else "Updated"
            self.stdout.write(f"  {action}: {product.name} ({product.category})")

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} products!"))
