# Generated by Django 4.2.30 on 2026-10-07 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=orders.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('governorate', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery (الدفع عند الاستلام)'), ('card', 'Credit / Debit Card (بطاقة بنكية)'), ('vodafone_cash', 'Vodafone Cash (فودافون كاش)'), ('instapay', 'InstaPay (انستاباي)')], default='cod', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Review (قيد المراجعة)'), ('verified', 'Verified / Paid (تم الدفع والتحقق)'), ('paid_on_delivery', 'To be Paid on Delivery (دفع عند الاستلام)'), ('failed', 'Failed (فشل الدفع)')], default='pending', max_length=30)),
                ('card_network', models.CharField(blank=True, max_length=20, null=True)),
                ('masked_card', models.CharField(blank=True, max_length=30, null=True)),
                ('gateway_note', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('receipt_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('placed', 'Order Placed (تم استلام الطلب)'), ('confirmed', 'Confirmed (تم تأكيد الطلب)'), ('shipped', 'Shipped (تم الشحن)'), ('out_for_delivery', 'Out for Delivery (في الطريق للتسليم)'), ('delivered', 'Delivered (تم التوصيل بنجاح)'), ('cancelled', 'Cancelled (ملغي)')], default='placed', max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
