# Generated by Django 4.2.30 on 2026-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English product name', max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', help_text='Arabic product name', max_length=200)),
                ('category', models.CharField(choices=[('Skin Care', 'Skin Care'), ('Hair Care', 'Hair Care'), ('Eye Care', 'Eye Care')], default='Skin Care', max_length=100)),
                ('category_ar', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EGP', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.CharField(blank=True, default='', help_text='Optional fallback image URL or asset path', max_length=500)),
                ('badge', models.CharField(blank=True, default='', help_text='Badge text in English (e.g. Best Seller, New)', max_length=50)),
                ('badge_ar', models.CharField(blank=True, default='', help_text='Badge text in Arabic', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='English description')),
                ('description_ar', models.TextField(blank=True, default='', help_text='Arabic description')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of key benefits in English')),
                ('benefits_ar', models.JSONField(blank=True, default=list, help_text='List of key benefits in Arabic')),
                ('how_to_use', models.TextField(blank=True, default='', help_text='How to use instructions in English')),
                ('how_to_use_ar', models.TextField(blank=True, default='', help_text='How to use instructions in Arabic')),
                ('ingredients', models.TextField(blank=True, default='', help_text='Ingredients in English')),
                ('ingredients_ar', models.TextField(blank=True, default='', help_text='Ingredients in Arabic')),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
    ]
